# name: Pull Request Checks
# on:
#   pull_request:
#     types:
#       - opened

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check out code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: 14

#     - name: Install dependencies
#       run: npm install

<<<<<<< HEAD
    # - name: Linting
    #   run: npm run lint
=======
#     - name: Linting
#       run: npm run lint
>>>>>>> d746417 (test-directly)

#     - name: Unit Tests
#       run: npm test

<<<<<<< HEAD
    # - name: Test Coverage
    #   run: npm run test:coverage
=======
#     - name: Test Coverage
#       run: npm run test:coverage
>>>>>>> d746417 (test-directly)

#     - name: Build
#       run: npm run build
